version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kuraberu-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-158mysr7lvwl2"
s3_prefix = "kuraberu-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" ChannelType=\"LIFF\""
image_repositories = []
