# Stack:LINE-UseCase-HairSalon-Layer
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Kuraberu-layer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - sample
      - prod
    Default: dev

Mappings:
  EnvironmentMap:
    dev:
      LayerName: KuraberuLAYER
    prod:
      LayerName: KuraberuLAYER

Resources:
  KuraberuLayerDev:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: layer
      Description: LambdaLayer
      CompatibleRuntimes: 
        - python3.8
      LayerName: !FindInMap [EnvironmentMap, !Ref Environment, LayerName]
    Metadata:
      BuildMethod: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KuraberuLayerDev:
    Description: "KuraberuLayerDev Layer ARN"
    Value: !Ref KuraberuLayerDev
  KuraberuLayerName:
    Description: "KuraberuLayerDev Layer Name"
    Value: !FindInMap [EnvironmentMap, !Ref Environment, LayerName]
    Export:
      Name: KuraberuLayerDev